### ISSUE TITLE
Relacionamento N:N incorreto da tabela de Matrículas

### ISSUE THREAD

**Issue by julianormgalli** [poo-ifpr/sistema_academico#1]
No mapeamento da tabela matricula, composta pelas tabelas Aluno e Curso, a tabela matrícula é somente uma tabela composta pelas chaves estrangeiras e sem nenhuma restrição (além de chave estrangeira), o que possibilita que vários registros **idênticos** sejam inseridos. 

Falta uma chave primária composta dos atributos curso_id e aluno_id.

**Comment by everaldo** [comment]
Olá, Juliano! Existem várias formas de resolver esse problema.

Apenas seguimos as especificações da apostila do prof. Paulo.

Outra alternativa seria trocar List<> por Set<>, visto que Set não permite elementos repetidos.

O programador deve escolher se as restrições serão feitas pelo banco de dados ou validadas utilizando lógica de programação.

Este tópico propõe algumas soluções:

http://stackoverflow.com/questions/3473978/manytomany-relationship-using-jpa-with-hibernate-provider-is-not-creating-primar

Vou atualizar nas próximas aulas.

Atenciosamente,
Everaldo

**Comment by julianormgalli** [comment]
Troquei o List<> para Set<> e funcionou.
Obrigado.

**Comment by everaldo** [comment]
@julianormgalli , agradeço os comentários. Eu não havia prestado atenção neste detalhe.
